### ISSUE TITLE
[Android] Issues with Half-Life: Blue Shift, Half-Life: Opposing Force

### ISSUE THREAD

**Issue by JORGETECH** [FWGS/xash3d#169] opened 2016-08-24 11:15 UTC
I recently discovered this project and I feel amazed for the amazing work you've done, but I am having some problems on the Android build with mods and expansions.

Half-Life: Blue Shift does not spawn the armor and helmet neccessary for playing the game normally, everything else seems fine. That was under the normal Xash3D launcher app but then I tried the Half-Life: Blue Shift launcher I found for Xash3D and that solved the armor and helmet spawning issue, however all the animations for weapons were broken (the models are rendered but the weapons do not move under any circunstanches), ignoring that issue the game seemed playable.

Half-Life: Opposing Force is unplayable. The Hazard Couse can't even be started because the NPC that gives you instructions does not spawn and the doors won't open. The intro does not finish because the pñane that is supposed to crash does not crash as it should do. I did not test gameplay after that but I guess it has the same armor issue as Blue Shift.

Lastly I tried Poke646, some kind of total conversion. I tried the WON version. First of all the Hazard Course cannot be completed because the pipe (Crowbar replacement) does not spawn, the HUD graphics are not canged and the custom weapon models were not there, only the Half-Life weapon models could be obtained. I will have to try with the SteamPipe patch if the same happens. (EDIT: The same happens with the steam patch)

If all these issues are caused because I did not configure something properly please feel free to tell me. Otherwise I would this issues with mod/expansions compatibility to be fixed.

Thanks in advance,
JORGETECH

**Comment by a1batross** [comment] 2016-08-24 11:43
Thanks for your issue!
Android version of Xash3D can't work with binaries compiled for Windows and Linux. (architecture, OS differences). So mods must be separately ported from it's source code.

Blue Shift is already done as "mod", you can download it from https://github.com/mittorn/BS-android/releases/. Must work flawlessly even with 0.18. :)

Opposing Force requires REALLY big work on it. So it's not available for Android yet :(

Poke646 requires porting too. If there was be a source code, I'd ported it.

**Comment by fuzun** [comment] 2016-08-24 12:00
@a1batross Can't this be done with virtualization? qemu? without recompiling.
Also https://github.com/SamVanheer/HLEnhanced this project soon may have opposing force support, but I am not sure, check it out.

**Comment by JORGETECH** [comment] 2016-08-24 12:07
I also think there is a possibility to do it through virtualization.

BTW a1batross the animations for Blue Shift weapons are present when I use the Blue Shift launcher (the same you linked to in your reply). Any fix for that?

**Comment by a1batross** [comment] 2016-08-24 12:35
@fuzun @JORGETECH mittorn already did this in separate project: XashDS Android. (https://github.com/FWGS/xashds-android/releases)

It's a linux dedicated server running in QEMU or Exagear. 

And yes. animations from Blue Shift Launcher is an old engine bug, which was completely fixed in 0.17. BShift just don't updated. 
You can workaround this by executing `cl_lw 0` in game console.

**Comment by CrusoeDaWolf** [comment] 2016-08-24 16:00
@a1batross Actually, the same person who made the SteamPipe patch for Poke646 released the source code.
You can find it here: https://github.com/malortie/halflife/tree/mod-hl-poke646

The thing is, the SteamPipe patch of Poke646 uses the 'mp3' command (Which isn't in Xash yet at least) instead of FMOD.

**Comment by a1batross** [comment] 2016-08-24 16:11
I think it can be ported easily. :)

**Comment by CrusoeDaWolf** [comment] 2016-08-24 16:21
Agreed. :D

Just don't expect me to do it. I have no idea what to do xP

Also, how would porting Deathmatch Classic to Android go about?

**Comment by a1batross** [comment] 2016-08-24 16:25
Someone worked on it but not released. Same for Ricochet port.
They are multilplayer mods. Without game servers they are useless.

**Comment by CrusoeDaWolf** [comment] 2016-08-24 16:30
I'll host one. Speaking of DMC, something weird I noticed.

So, I'm using the WON version and for some reason, when cl_lw is on 0, you can't switch through weapons. When you do, it fires the weapon instead. Not sure if this is a bug with Xash or DMC.

**Comment by a1batross** [comment] 2016-08-24 16:32
I launched Steam version of DMC under Xash and... stuck in level. I never opened DMC anymore.

(for using Steam version you need to put some libraries from Steam HL to Xash folder, such as filesystem_stdio.so, libtier0.so, maybe vstdlib)

**Comment by CrusoeDaWolf** [comment] 2016-08-24 16:36
Ah. There is a problem with one of the maps where the spawn might get you stuck. I'm guessing that may be a problem with DMC itself. 

Also, with cl_lw 1, the lightning gun doesn't have its firing effect.

I'm guessing that a DMC port could be easy though, since it is a small mod.

**Comment by a1batross** [comment] 2016-08-24 16:38
It was my lovely dm6, as I remember. 

Do you trying to play with cl_lw 1 on our fork? Uncle Mike's 3366 build have broken local weapons. 
Also, don't forget to execute cl_predict 1. Otherwise cl_lw 1 wil not work.

**Comment by CrusoeDaWolf** [comment] 2016-08-24 16:40
The problem is in both, SDL fork and Uncle Mike's 3366. cl_predict is on 1.

**Comment by JORGETECH** [comment] 2016-08-25 12:13
"cl_lw 0" fixes all the animation issues with Blue Shift.

I hope we get a Poke646 port because I think it is one of the best mods for Half-Life.

I suggest you start to experiment with qemu, I think it is a very good way to work around the DLLs or SOs issues instead of rewriting every mod (very exhaustive proccess).

**Comment by CrusoeDaWolf** [comment] 2016-08-25 15:26
I don't believe you entirely rewrite a mod. Take a look at this section in the wiki:https://github.com/FWGS/xash3d/wiki/Mod-Porting-Guide

**Comment by JORGETECH** [comment] 2016-08-25 20:47
Yeah but it also should have the option to have qemu emulation, maybe in a separate package.

**Comment by CrusoeDaWolf** [comment] 2016-08-25 21:55
A separate package would be nice, but would about lower end devices? They may not handle it as well.

**Comment by a1batross** [comment] 2016-08-25 23:27
I am saying this again.

Mittorn did XashDS Android with QEMU/Exagear support. This app can run
almost any mod in background server.

BTW there is no documentation in English for XashDS.
26.08.2016 3:55 пользователь "CrusoeDaWolf" <notifications@github.com>
написал:

**Comment by CrusoeDaWolf** [comment] 2016-08-25 23:58
Isn't XashDS just a dedicated server for Android though? Or does it allow you to play said mod?

**Comment by nekonomicon** [comment] 2016-08-26 05:14
Dedicated server with dll loader(winewrapper). You can use rcon with xashds for some singleplayer mods.

**Comment by hathlife** [comment] 2016-08-26 14:31
Is it possible to port Condition Zero:Deleted Scenes to android?

**Comment by a1batross** [comment] 2016-08-26 15:47
@hathlife Nope.

**Comment by nekonomicon** [comment] 2016-08-26 23:54
I'm tried merge poke646(without vendetta) to hlsdk-xash3d.
It works fine for me on FreeBSD, but i'm not tested on Android yet.
https://github.com/nekonomicon/hlsdk-xash3d/tree/poke646

**Comment by CrusoeDaWolf** [comment] 2016-08-27 00:29
:D Awesome! Progress!

**Comment by CrusoeDaWolf** [comment] 2016-08-27 02:53
@nekonomicon I compiled the libraries and tested them. Everything seems to work, however I've only tried the hazard course so I'm unsure if the in-game sound track will work under Xash.

**Comment by nekonomicon** [comment] 2016-08-28 19:23
Vendetta:
https://github.com/nekonomicon/hlsdk-xash3d/tree/poke646_vendetta
I replaced "mp3" on "play". Is it good solution?

**Comment by CrusoeDaWolf** [comment] 2016-08-28 19:27
I saw. Probably should be.

**Comment by mittorn** [comment] 2016-08-29 13:36
@nekonomicon it is better to add alias for it in xash3d ofcause.

**Comment by nekonomicon** [comment] 2016-08-29 16:41
@mittorn, revert then?

**Comment by mittorn** [comment] 2016-09-03 03:29
No. Wait before it fixed in engine.

**Comment by fuzun** [comment] 2016-09-17 23:12
@a1batross Did not mittorn port opposing force to xash3d?
I saw this but did not understand:

http://4pda.ru/forum/index.php?showtopic=650049&st=4280

**Comment by nekonomicon** [comment] 2016-09-18 07:17
@fuzun, client only. It's required xashds.
Restored server implementation not finished.
https://github.com/FWGS/halflife/tree/branch-malortie-op4

**Comment by fuzun** [comment] 2016-09-18 12:07
@nekonomicon Why is not that in https://github.com/FWGS/hlsdk-xash3d ? What do you mean by server? hlsdk-xash3d contains server (hl).
For example if I make a mod, should I work both for hlsdk-xash3d and halflife ? halflife only required for engine compatibility ?

**Comment by nekonomicon** [comment] 2016-09-18 12:26
@fuzun, first xash3d sdl releases used xashxt client and hlsdk2.4 server.

>What do you mean by server?

opfor.dll reimplementation not finished.

**Comment by nekonomicon** [comment] 2016-09-27 22:11
@JORGETECH, Poke646 android port ready!

https://github.com/nekonomicon/Poke646-android/releases/tag/1.0

https://github.com/nekonomicon/Poke646_Vendetta-android/releases/tag/1.0

**Comment by a1batross** [comment] 2016-09-27 22:25
@nekonomicon, incredible!

2016-09-28 1:11 GMT+03:00 Andrey Akhmichin <notifications@github.com>:

**Comment by JORGETECH** [comment] 2016-10-15 10:12
> 
@JORGETECH, Poke646 android port ready!
https://github.com/nekonomicon/Poke646-android/releases/tag/1.0
https://github.com/nekonomicon/Poke646_Vendetta-android/releases/tag/1.0

@nekonomicon Good job! I will try it when I can.

**Comment by a1batross** [comment] 2016-11-06 15:41
Not a bug.

**Closed by a1batross** 2016-11-06 15:41 UTC
