### ISSUE TITLE
CL_IsThirdPerson should not be called on disconnecting client

### ISSUE THREAD

**Issue by mittorn** [FWGS/xash3d#305] opened 2017-10-29 07:34 UTC

**Comment by a1batross** [comment] 2017-10-29 14:45
It's by design should not be cached, as it engine does now. We should or move it somewhere else, or replace cl.thirdperson by CL_IsThirdPerson everywhere.

**Comment by a1batross** [comment] 2017-12-11 19:48
Fixed by https://github.com/FWGS/xash3d/commit/267935b7355e2e724a88e76f8eeced4510175bda

**Closed by a1batross** 2017-12-11 19:48 UTC
