### ISSUE TITLE
[Mod Launcher Request] Brutal Half Life

### ISSUE THREAD

**Issue by Hmmarch** [FWGS/xash3d#239] opened 2017-03-05 19:27 UTC
I have seen a source code for Brutal HalfLife for Xash:
https://github.com/RAINBOW2000/BHL
Can the Team make maybe a BHL Launcher?

**Comment by nekonomicon** [comment] 2017-03-05 20:04
He is our teammate.
He is working on bhl android port.

**Comment by Hmmarch** [comment] 2017-03-05 20:58
Oh thanks god.
I love the CL:CM Port that he Made.
(Oh and how the fuck can i bind the Controller Keys?)

**Comment by a1batross** [comment] 2017-03-06 04:00
Don't be rude. Controller keys are mapped like any other keys, in Controls
menu. (Press A to select the key)
05.03.2017 23:58 пользователь "Hmmarch" <notifications@github.com> написал:

**Comment by a1batross** [comment] 2017-03-07 14:55
Not a bug, closing as invalid.

**Closed by a1batross** 2017-03-07 14:55 UTC
